---
title: "Untitled"
author: "Marcin Kosiński"
date: "15 grudnia 2015"
output: html_document
---

# Data preparations

```{r}
library(coxphSGD)
set.seed(456)
dataCox <- function(N, lambda, rho, x, beta, censRate){
  
  # real Weibull times
  u <- runif(N)
  Treal <- (- log(u) / (lambda * exp(x %*% beta)))^(1 / rho)
  
  # censoring times
  Censoring <- rexp(N, censRate)
  
  # follow-up times and event indicators
  time <- pmin(Treal, Censoring)
  status <- as.numeric(Treal <= Censoring)
  
  # data set
  data.frame(id=1:N, time=time, status=status, x=x)
}

x <- matrix(sample(0:1, size = 20000, replace = TRUE), ncol = 2)

dataCox(10^4, lambda = 5, rho = 0.5, x, beta = c(-0.5,2), censRate = 0.2) -> dCox

library(dplyr)
dCox %>%
  dplyr::arrange(time) -> dCoxArr

# assuming observations are sorted by time
full_cox_loglik <- function(beta1, beta2, x1, x2, censored){
  sum(rev(censored)*(beta1*rev(x1) + beta2*rev(x2) -
                       log(cumsum(exp(beta1*rev(x1) + beta2*rev(x2))))))
  # #   sum(rev(censored)*(beta1*rev(x1) + beta2*rev(x2))) -
  # #     sum(rev(censored)*log(cumsum(exp(beta1*rev(x1)+beta2*rev(x2)))))
  #   n <- length(censored)
  #   part <- numeric(n)
  #   for(i in 1:n){
  #     part[i] <- beta1*x1[i:n]+beta2*x2[i:n] - log(sum(exp(beta1*x1[i:n]+beta2*x2[i:n])))
  #   }
  #   sum(part)
}
```


# sim 1 - 1/x

```{r}
sample(1:90, size = 10^4, replace = TRUE) -> group

split(dCox, group) -> dCox_splitted
coxphSGD(Surv(time, status)~x.1+x.2, data = dCox_splitted, epsilon = 1e-03,
         learningRates = function(x){1/x}, beta_0 = c(0,0), max.iter = 1*90) -> estimates

lapply(estimates$coefficients, function(beta){
  full_cox_loglik(beta[1], beta[2], dCoxArr$x.1, dCoxArr$x.2, dCoxArr$status)
}) %>% unlist -> full_cox_loglik_sim
full_cox_loglik_sim
plot(full_cox_loglik_sim)
```


# sim 2 - 1/100*sqrt(x)

```{r}
sample(1:90, size = 10^4, replace = TRUE) -> group

split(dCox, group) -> dCox_splitted
coxphSGD(Surv(time, status)~x.1+x.2, data = dCox_splitted, epsilon = 1e-03,
         learningRates = function(x){1/100*sqrt(x)}, beta_0 = c(0,0), max.iter = 1*90) -> estimates

lapply(estimates$coefficients, function(beta){
  full_cox_loglik(beta[1], beta[2], dCoxArr$x.1, dCoxArr$x.2, dCoxArr$status)
}) %>% unlist -> full_cox_loglik_sim
full_cox_loglik_sim
plot(full_cox_loglik_sim)
```


# sim 3 - 1/100*sqrt(x), 5 epochs

```{r}
sample(1:90, size = 10^4, replace = TRUE) -> group

split(dCox, group) -> dCox_splitted
coxphSGD(Surv(time, status)~x.1+x.2, data = dCox_splitted, epsilon = 1e-03,
         learningRates = function(x){1/100*sqrt(x)}, beta_0 = c(0,0), max.iter = 5*90) -> estimates

lapply(estimates$coefficients, function(beta){
  full_cox_loglik(beta[1], beta[2], dCoxArr$x.1, dCoxArr$x.2, dCoxArr$status)
}) %>% unlist -> full_cox_loglik_sim
full_cox_loglik_sim
plot(full_cox_loglik_sim)
```
